---
- hosts: all
  connection: local

  vars_files:
    - ../defaults/main.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - geerlingguy.homebrew

  tasks:
     - include: ansible-setup.yml
     - include: ruby-setup.yml
     - include: macos-defaults.yml
